   ### Cartpanda order.paid
   POST http://app.votresante.site/api/cartpanda/webhook
   Content-Type: application/json

   {
     "id": "evt_test",
     "type": "order.paid",
     "data": {
       "order": {
         "id": "ord_1234",
         "number": "#0002",
         "customer": {
           "email": "acesso@cartpanda.com",
           "first_name": "Cartpanda",
           "last_name": "Company"
         }
       }
     }
   }